- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/google/go-cmp v0.5.2, I hope it works.
```json
{
"major": false,
"minor": true,
"patch": false
}
```
> Update github.com/google/go-cmp from v0.4.0 to v0.5.2

- go.mod
- go.sum
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
Here is github.com/stretchr/testify v1.6.1, I hope it works.
```json
{
"major": false,
"minor": false,
"patch": true
}
```
> Update github.com/stretchr/testify from v1.6.0 to v1.6.1

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/handlers.go
- vendor/github.com/thepwagner/action-update/actions/updateaction/handlers.go
- vendor/github.com/thepwagner/action-update/updater/group.go
- vendor/github.com/thepwagner/action-update/updater/updater.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.3, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.2 to v0.0.3

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.5, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.3 to v0.0.5

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/pullrequest.go
- vendor/github.com/thepwagner/action-update/repo/commit.go
- vendor/github.com/thepwagner/action-update/repo/git.go
- vendor/github.com/thepwagner/action-update/repo/github.go
- vendor/github.com/thepwagner/action-update/repo/pullrequest.go
- vendor/github.com/thepwagner/action-update/updater/signed.go
- vendor/github.com/thepwagner/action-update/updater/update.go
- vendor/github.com/thepwagner/action-update/updater/updater.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.10, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.8 to v0.0.10

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/repo/git.go
- vendor/github.com/thepwagner/action-update/repo/github.go
- vendor/github.com/thepwagner/action-update/updater/update.go
- vendor/github.com/thepwagner/action-update/updater/updater.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.11, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.10 to v0.0.11

- go.mod
- go.sum
- gomodules/applyupdate.go
- gomodules/check.go
- gomodules/check_test.go
- gomodules/dependencies.go
- gomodules/updater.go
- vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
- vendor/golang.org/x/mod/modfile/print.go
- vendor/golang.org/x/mod/modfile/read.go
- vendor/golang.org/x/mod/modfile/rule.go
- vendor/golang.org/x/mod/module/module.go
- vendor/golang.org/x/xerrors/LICENSE
- vendor/golang.org/x/xerrors/PATENTS
- vendor/golang.org/x/xerrors/README
- vendor/golang.org/x/xerrors/adaptor.go
- vendor/golang.org/x/xerrors/codereview.cfg
- vendor/golang.org/x/xerrors/doc.go
- vendor/golang.org/x/xerrors/errors.go
- vendor/golang.org/x/xerrors/fmt.go
- vendor/golang.org/x/xerrors/format.go
- vendor/golang.org/x/xerrors/frame.go
- vendor/golang.org/x/xerrors/go.mod
- vendor/golang.org/x/xerrors/internal/internal.go
- vendor/golang.org/x/xerrors/wrap.go
- vendor/modules.txt
Closes https://github.com/thepwagner/action-update-go/issues/86
> Gomodules extracted 120pre

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/updater/updater.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.12, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.11 to v0.0.12

- go.mod
- go.sum
- vendor/github.com/bmatcuk/doublestar/v2/.gitignore
- vendor/github.com/bmatcuk/doublestar/v2/.travis.yml
- vendor/github.com/bmatcuk/doublestar/v2/LICENSE
- vendor/github.com/bmatcuk/doublestar/v2/README.md
- vendor/github.com/bmatcuk/doublestar/v2/UPGRADING.md
- vendor/github.com/bmatcuk/doublestar/v2/doublestar.go
- vendor/github.com/bmatcuk/doublestar/v2/go.mod
- vendor/github.com/thepwagner/action-update/actions/env.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.13, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.12 to v0.0.13

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/env.go
- vendor/github.com/thepwagner/action-update/actions/updateaction/env.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.14, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.13 to v0.0.14

- go.mod
- go.sum
- vendor/github.com/bmatcuk/doublestar/v2/README.md
- vendor/github.com/bmatcuk/doublestar/v2/doublestar.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.16, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.15 to v0.0.16

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/release.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.20, I hope it works.
> Update github.com/thepwagner/action-update from v0.0.17 to v0.0.20

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.21, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.21

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/repositorydispatch.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.22, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.22

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.23, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.23

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/release.go
- vendor/github.com/thepwagner/action-update/actions/updateaction/repositorydispatch.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.24, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.24

- go.mod
- go.sum
- vendor/github.com/bmatcuk/doublestar/v2/README.md
- vendor/github.com/bmatcuk/doublestar/v2/doublestar.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.27, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.27

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.32, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.32

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/repositorydispatch.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.33, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.33

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.35, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.35

- go.mod
- go.sum
- vendor/github.com/thepwagner/action-update/actions/updateaction/repositorydispatch.go
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.36, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.36

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.37, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.37

- go.mod
- go.sum
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
Here is github.com/stretchr/testify v1.7.0, I hope it works.
> Update github.com/stretchr/testify from v1.6.1 to v1.7.0

- go.mod
- go.sum
- vendor/github.com/sirupsen/logrus/CHANGELOG.md
- vendor/github.com/sirupsen/logrus/entry.go
- vendor/modules.txt
Here is github.com/sirupsen/logrus v1.8.0, I hope it works.
[changelog](https://github.com/sirupsen/logrus/blob/v1.8.0/CHANGELOG.md)
> Update github.com/sirupsen/logrus from v1.7.1 to v1.8.0

- go.mod
- go.sum
- vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.42, I hope it works.
> Update github.com/thepwagner/action-update from  to v0.0.42
