thepwagner/action-update-go

action.yml, actions/schedule.go, cmd/env.go, updater/dockerurl/check.go, updater/dockerurl/check_test.go
This PR adds an `updater` input, which allows toggling between the included `updater.Updater` implementations on a repository.
Longer term I don't like the idea of having _every_ updater in the same repository; but while I'm throwing stuff at the wall for v0 it's the easiest way to keep implementations in sync.
Then it continues to change how `pre-release` releases are handled in the `dockerurl` updater:
* previously pre-releases were always ignored
* now pre-releases will be considered if the current release is also a pre-release
This is pretty specifically for https://github.com/bufbuild/buf/releases , which is always a pre-release? 🤷 , I just want to compile protobufs.
=> selectable `updater` + dockerurl pre-release

updater/gomod/applyupdate.go, updater/gomod/applyupdate_test.go, updater/gomod/check.go, updater/gomod/check_test.go, updater/gomod/dependencies_test.go, updater/gomod/testdata/gopkg/go.mod, updater/gomod/testdata/gopkg/go.sum, updater/gomod/testdata/gopkg/main.go, updater/gomod/testdata/replace/go.mod
I encountered as `gopkg.in/src-d/go-git.v3`; I used `yaml` for the harness as it's use internally.
=> gopkg.in support

updater/dockerurl/applyupdate.go, updater/dockerurl/applyupdate_test.go, updater/dockerurl/testdata/buf/Dockerfile
Don't assume the shasum file is for a single asset - look the corresponding file in the previous shasum asset, then find it in the new one.
Added `bufbuild/buf` as a sample that needs this.
=> dockerurl: shasum matching

updater/gomod/applyupdate.go, updater/gomod/applyupdate_test.go, updater/gomod/check.go, updater/gomod/check_test.go, updater/gomod/dependencies.go, updater/gomod/dependencies_test.go, updater/gomod/testdata/multimodule/cmd/go.mod, updater/gomod/testdata/multimodule/cmd/go.sum, updater/gomod/testdata/multimodule/cmd/main.go, updater/gomod/testdata/multimodule/common/common.go, updater/gomod/testdata/multimodule/common/go.mod, updater/gomod/testdata/multimodule/common/go.sum, updatertest/updatertest.go
This changes the `gomodules.Updater` to operate recursively on all `go.mod` files under the root.
This allows operating on repositories that contain multiple go modules, including internal dependencies.
Tests cover operating on multiple `go.mod` files, or focusing the updater on a single `go.mod` path.
The idea is some new input may change the updater root to a subpath: you _can_ run configure each submodule individually, but recursive-by-default is a feature I liked from the `docker*` updaters.
=> gomodules: multimodule support

.golangci.yml, action.yml, actions/schedule.go, cmd/env.go, repo/commit.go, repo/git.go, repo/git_test.go, repo/github.go, repo/github_test.go, repo/pullrequest.go, repo/pullrequest_test.go, updater/mockrepo_test.go, updater/update.go, updater/updater.go, updater/updater_test.go
Continues #53, extending `Repo.Push()` to accept varargs `[]updater.Updater`.
This allows batched updates to include details about every update, replacing the generic "multiple updates" placeholders and finishing a `TODO`.
In `GitHubRepo.Push()`, the `{major:, minor:, patch:}` visible blob in PRs is replaced with an invisible HMAC-ed blob that encodes the full update details.
This will eventually be parsed, bringing back the ability to skip updates that have closed PRs. Previously that relied on parsing the target update from branch names, but that branch naming became optional with batched updates.
=> Batched push

actions/pullrequest.go, actions/pullrequest_test.go, repo/pullrequest.go, repo/pullrequest_test.go, updater/branch.go, updater/branch_test.go, updater/signed.go, updater/signed_test.go, updater/updater.go, updater/updater_test.go
Continuing from #71 , we can parse the `SignedUpdateDescriptor` from the PR description - that's a better source of truth than the PR's branch.
Then since nothing is using that code any more, ✂️ .
=> Remove BranchNamer.Parse

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.3, I hope it works.
=> Update golang from 1.15.0 to 1.15.3

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.32.0-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.31.0-alpine to v1.32.0-alpine

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.32.2-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.32.0-alpine to v1.32.2-alpine

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.4, I hope it works.
=> Update golang from 1.15.3 to 1.15.4

go.mod, go.sum, vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.26, I hope it works.
=> Update github.com/thepwagner/action-update from  to v0.0.26

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.5, I hope it works.
=> Update golang from 1.15.4 to 1.15.5

go.mod, go.sum, vendor/github.com/thepwagner/action-update/actions/handlers.go, vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.28, I hope it works.
=> Update github.com/thepwagner/action-update from  to v0.0.28

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.33.0-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.32.2-alpine to v1.33.0-alpine

go.mod, go.sum, vendor/golang.org/x/mod/modfile/read.go, vendor/golang.org/x/mod/modfile/rule.go, vendor/golang.org/x/mod/module/module.go, vendor/golang.org/x/mod/semver/semver.go, vendor/golang.org/x/mod/zip/zip.go, vendor/modules.txt
Here is golang.org/x/mod v0.4.0, I hope it works.
=> Update golang.org/x/mod from v0.3.0 to v0.4.0

go.mod, go.sum, vendor/modules.txt
Here is github.com/thepwagner/action-update v0.0.29, I hope it works.
=> Update github.com/thepwagner/action-update from  to v0.0.29

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.6, I hope it works.
=> Update golang from 1.15.5 to 1.15.6

action.yml
This was mostly implemented, but `action.yaml` didn't define+forward the input.
=> Optional `go mod tidy`

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.34.1-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.33.0-alpine to v1.34.1-alpine

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.35.0-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.34.1-alpine to v1.35.0-alpine

go.mod, go.sum, vendor/golang.org/x/mod/modfile/rule.go, vendor/modules.txt
Here is golang.org/x/mod v0.4.1, I hope it works.
=> Update golang.org/x/mod from v0.4.0 to v0.4.1

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.15.8, I hope it works.
=> Update golang from 1.15.7 to 1.15.8

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.0, I hope it works.
=> Update golang from 1.15.8 to 1.16.0

go.mod, go.sum, vendor/golang.org/x/mod/modfile/rule.go, vendor/golang.org/x/mod/module/module.go, vendor/modules.txt
Here is golang.org/x/mod v0.4.2, I hope it works.
=> Update golang.org/x/mod from v0.4.1 to v0.4.2

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.1, I hope it works.
=> Update golang from 1.16.0 to 1.16.1

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.2, I hope it works.
=> Update golang from 1.16.1 to 1.16.2

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.3, I hope it works.
=> Update golang from 1.16.2 to 1.16.3

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.4, I hope it works.
=> Update golang from 1.16.3 to 1.16.4

script/tools/golangci-lint/Dockerfile
Here is golangci/golangci-lint v1.40.0-alpine, I hope it works.
=> Update golangci/golangci-lint from v1.39.0-alpine to v1.40.0-alpine

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.5, I hope it works.
=> Update golang from 1.16.4 to 1.16.5

.github/workflows/ci.yaml, .github/workflows/update.yaml, Dockerfile
Here is golang 1.16.6, I hope it works.
=> Update golang from 1.16.5 to 1.16.6
